# Generated by Django 5.0.3 on 2024-03-07 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('visibility', models.PositiveIntegerField(choices=[(0, 'Invisible Everywhere'), (1, 'Deactivated'), (2, 'Visible')])),
            ],
        ),
        migrations.CreateModel(
            name='CourseStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название Потока', max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tariff name', max_length=255)),
                ('stream', models.ForeignKey(help_text='Поток', on_delete=django.db.models.deletion.CASCADE, to='payment.coursestream')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('payed', models.BooleanField(default=False)),
                ('payed_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('payed_currency', models.CharField(blank=True, default='', max_length=4)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.courseinstance')),
            ],
        ),
    ]
